### ISSUE TITLE
The Data preprocessing pipeline does not work on mouse data

### ISSUE THREAD

**Issue by nieyage** [dyxmvp/Spatial_ATAC-seq#5]
Hi!
I have tested this pipeline on human data sets and it works, but it does not work on mouse data sets. I've only changed part of global varibales in Snakefile and barcodes file.
The modified parts are as follows:
`rawData_dir = "/md01/nieyg/project/spatial_ATAC_mmhs/data/rawdata/mouse" # raw sequencing data directory
processedData_dir = '/md01/nieyg/project/spatial_ATAC_mmhs/data/rawdata/Processed_data/' # processed sequencing data directory
fastq_ext = '.fastq.gz' # fastq file extension

core = 20 # threads to use
core_cellRanger = int(core*0.8) # threads to use in cellRanger
mem = 64 # memory to use in cellRanger

bbduk_dir = "/md01/nieyg/software/bbmap/bbduk.sh" # bbduk.sh directory
cellranger_dir = "/md01/nieyg/software/cellranger-spatial-atac/cellranger-atac" # cellranger-atac directory
ref_dir = "/md01/nieyg/ref/10X/refdata-cellranger-arc-mm10-2020-A-2.0.0/" # reference data directory`

This pipeline worked well until cell ranger step.
It reported an error: "Could not find any read pairs that were mapped in the correct orientation to the same primary contig with mapping quality > 30 to the primary contigs. Further execution is halted."

I found this file "SRR14492030_raw_qc_R1.fastq.gz"  to be much smaller than the one in human.

I don't know why this is, can you give me some advice?

**Comment by yxdeng-lab** [comment]
Can you tell me which dataset in the GEO you are analyzing?

**Comment by nieyage** [comment]
> Can you tell me which dataset in the GEO you are analyzing?
SRR18745416 and SRR14492030.

**Comment by yxdeng-lab** [comment]
Can you try the attached files? We used optimized chemistry for SRR18745416.  SRR14492030 is from V1 chemistry, which has very low data quality as discussed in the paper, and cannot be used for data analysis.
[hsrCUTA_Snakemake_chemV2.zip](https://github.com/dyxmvp/Spatial_ATAC-seq/files/10775507/hsrCUTA_Snakemake_chemV2.zip)

**Comment by nieyage** [comment]
> Can you try the attached files? We used optimized chemistry for SRR18745416. SRR14492030 is from V1 chemistry, which has very low data quality as discussed in the paper, and cannot be used for data analysis. [hsrCUTA_Snakemake_chemV2.zip](https://github.com/dyxmvp/Spatial_ATAC-seq/files/10775507/hsrCUTA_Snakemake_chemV2.zip)

SRR18745416 works well with this new pipeline. Thanks for the help!
